podcasts:
  3dcast: 3D-Podcast
  gwaren: Gebrauchtwaren-Podcast
audio_file_destination:
  development: ./tmp/files
  production: /usr/local/www/media
processing:
  mp3:
    bitrate: 128k
    sampling_rate: 44100
mail:
  sender: postmaster@a0s.de
  subject: Podcast-Datei steht bereit
