podcasts:
  bratwurst: Abenteuer Bratwurst
  gwaren: Gebrauchtwarenpodcast
audio_file_destination:
  development: ./tmp/files
  production: /usr/local/www/media
processing:
  mp3:
    bitrate: 128k
    sampling_rate: 44100
mail:
  sender: Podcast Upload<postmaster@a0s.de>
  subject_success: Podcast-Datei steht bereit
  subject_error: Fehler beim Verarbeiten der Podcast-Datei
